[tool.poetry]
name = "poetry-ros2"
version = "0.1.0"
description = "ros2 virtual environments"
authors = ["cpx <vision2cpx@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
gym = "=0.21.0"
gym-unity = "^0.26.0"
matplotlib = "^3.6.0"
mujoco = "^2.2.0"
mlagents-envs = "=0.28.0"
numpy = "^1.21.4"
onnx = "^1.12.0"
onnxruntime-gpu = "^1.13.1"
opencv-python = "^4.6.0"
pandas = "^1.5.1"
Pillow = "^8.4.0"
pymycobot = "^2.9.6"
pyserial = "^3.5"
qtconsole = "^5.2.1"
QtPy = "^1.11.2"
ray = "^1.8.0"
requests = "^2.22.0"
scipy = "^1.7.3"
# stable-baselines3 = "^1.6.2"
torch = {url = "https://download.pytorch.org/whl/cu113/torch-1.11.0%2Bcu113-cp38-cp38-linux_x86_64.whl"}
torchvision = {url = "https://download.pytorch.org/whl/cu113/torchvision-0.12.0%2Bcu113-cp38-cp38-linux_x86_64.whl"}
# torch = {version = "=1.11.0+cu113", source = "pytorch-cu113"}
# torchvision = {version = "=1.12.0+cu113", source = "pytorch-cu113"}
tqdm = "^4.63.1"
wandb = "*"
xgboost = "^1.5.1"

# [[tool.poetry.source]]
# name = "pytorch-cu113"
# url = "https://download.pytorch.org/whl/cu113"
# secondary = true

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.15.3"
nbformat = "^5.0.7"
notebook = "^6.5.2"
plotly = "^5.11.0"
tensorboard = "^2.9.1"

[tool.poetry.group.test.dependencies]
pytest = "^6.2.3"

[tool.poetry.group.docs.dependencies]
mkdocs-doxygen-snippets-plugin = "*"
mkdocs-material = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
